### ISSUE TITLE
_toc.yml automatisch erstellen

### ISSUE THREAD

**Issue by jhorzek** [Methods-Berlin/RTraining#35]
_toc.yml sollte automatisch basierend auf den Themen in Aufgaben_rmd erstellt werden. Die Reihenfolge wird durch die Nummerierung der Themen festgelegt.

**Comment by behnkec** [comment]
Ich habe überlegt, dass es vielleicht sinnvoll ist, die Kapitel Struktur von der RLernplattform zu übernehmen. 
Dann wäre eine Automatisierung vielleicht doch nicht praktikabel.
Was denkst du @jhorzek?

**Comment by jhorzek** [comment]
Stimmt, wahrscheinlich hilft das auch nicht wirklich weiter. 
Lass uns erst einmal beim aktuellen Vorgehen bleiben. Vielleicht wollen wir später noch Übungen hinzufügen, die über die RLernplattform hinaus gehen oder es gibt Themen auf der RLernplattform, für die noch keine Übungsaufgaben erstellt wurden. Dann wäre eine automatische Übernahme der Kapitel-Struktur schwierig.

**Comment by jhorzek** [comment]
Ich habe die gitHub action erweitert und eine [neue Funktion in rmd2myst ergänzt](https://github.com/Methods-Berlin/RTraining/blob/2524bcef4ff8fca42bd00ea71d219c0a2b216aaa/rmd2myst.R#L16). Wenn eine Rmd-Datei nicht in _toc.yml aufgeführt wird, dann wird automatisch ein neues Issue erstellt ([Beispiel](https://github.com/Methods-Berlin/RTraining/issues/56))
