### ISSUE TITLE
Umgang mit Lösungen

### ISSUE THREAD

**Issue by jhorzek** [Methods-Berlin/RTraining#58]
Wir bieten aktuell zwei Möglichkeiten an, die Aufgaben zu bearbeiten: 

1. Aufgaben als Rmd herunterladen und in RStudio bearbeiten
2. Aufgaben interaktiv über mybinder bearbeiten

Bei 1. stehen jedoch bereits alle Lösungen im Dokument. Wir sollten hier noch einen besseren Weg finden. Z.B. könnten wir einen eigenen tag für Lösungen einbauen. Alle Felder mit diesem Tag werden dann automatisch aus dem Übungs - Rmd entfernt und Studierende können die Aufgaben dann ohne Lösungen herunterladen. Die Lösungen sind entweder online verfügbar oder wir bieten noch einen separaten Download für das Rmd mit Lösungen an.

**Comment by behnkec** [comment]
Vielleicht könnte man eine gesonderte Funktion (ähnlich wie rmd2myst) schreiben, die eine Kopie des rmd in einem neuen Ordner speichert und dabei alle chunks mit dem Label `{r loesung}` löscht. Die Download Funktion in rmd2myst könnte dann direkt auf diesen neuen Ordner zu greifen. Dann können wir immer noch beliebig einen zweiten Download Button hinzufügen, indem die Lösungen noch vorhanden sind.

**Comment by jhorzek** [comment]
Ja, das klingt gut! Wir sollten einen Tag für den Start der Lösung und das Ende der Lösung einfügen. Vielleicht könnten wir einfach html-Kommentare nehmen; die würden dann auch nicht auf unserer Webseite auftauchen. Z.B.

**Comment by jhorzek** [comment]
#69
