### ISSUE TITLE
Lösungen für Aufgaben

### ISSUE THREAD

**Issue by jhorzek** [Methods-Berlin/RTraining#7]
Wir sollten schauen, wie wir die Lösungen der Übungsaufgaben am besten anzeigen. `<aside>` hat in myst nicht funktioniert, aber vielleicht geht `<details>` ?

**Comment by behnkec** [comment]
Es gibt in Myst [Dropdowns](https://jupyterbook.org/en/stable/content/components.html#dropdowns), die wie Code Cells integriert werden. Allerdings weiß ich nicht genau, wie wir das dann im R-Markdown integrieren.

**Comment by jhorzek** [comment]
Ich habe mich auch schon durch ein paar Dropdown-Varianten durchprobiert und leider konnte ich in keiner Text und Code kombinieren. Das einzige, was bei mir funktioniert, ist für Text `<details>` zu nutzen und für code `:tags: [hide-cell]`

**Comment by behnkec** [comment]
Bei mir ist es genauso.
